"""
Crime Report API — /api/v1/crime-reports
=========================================
All endpoints require authentication.

Auto-assigned fields (never accepted from client)
-------------------------------------------------
crime_number    Generated by PostgreSQL sequence: CR-{YEAR}-{SEQ:06d}
reporter_id     Set to current_user.id
status          Always forced to OPEN on creation

Status transition matrix (enforced by service)
----------------------------------------------
OPEN              → UNDER_INVESTIGATION | CLOSED
UNDER_INVESTIGATION → CLOSED | OPEN
CLOSED            → ARCHIVED | OPEN
ARCHIVED          → (terminal — no transitions)
"""
from datetime import datetime
from typing import Literal, Optional, Any, cast
import uuid

from fastapi import APIRouter, Depends, Query, Request, status
from sqlalchemy.ext.asyncio import AsyncSession

from app.api.dependencies import get_current_active_user
from app.core.enums.crime_status import CrimeStatus
from app.core.enums.priority import Priority
from app.db.session import get_db
from app.models.user import User
from app.schemas.common import PaginatedResponse, paginate
from app.schemas.crime_report import (
    CrimeReportCreate,
    CrimeReportDetailResponse,
    CrimeReportUpdate,
)
from app.services.crime_report_service import CrimeReportService

router = APIRouter()

_authenticated = Depends(get_current_active_user)


# ---------------------------------------------------------------------------
# Endpoints
# ---------------------------------------------------------------------------


@router.post(
    "",
    response_model=CrimeReportDetailResponse,
    status_code=status.HTTP_201_CREATED,
    summary="Create crime report",
)
async def create_crime_report(
    payload: CrimeReportCreate,
    request: Request,
    db: AsyncSession = Depends(get_db),
    current_user: User = _authenticated,
):
    """
    Create a new crime report. **Police Officer / Investigator / Admin.**

    Auto-assigned by backend
    ------------------------
    - `crime_number` — sequential, per-year: `CR-2026-000001`
    - `reporter_id` — always set to the authenticated user
    - `status` — always `OPEN`

    Business rules
    --------------
    - `category_id` must reference a non-deleted crime category.
    - `location_id` must reference a non-deleted crime location.
    - `incident_date` must not be in the future.

    Audit log is created automatically.
    """
    return cast(Any, await CrimeReportService.create(db, payload, current_user, request))


@router.get(
    "",
    response_model=PaginatedResponse[CrimeReportDetailResponse],
    summary="List crime reports",
)
async def list_crime_reports(
    # Pagination
    page: int = Query(1, ge=1, description="Page number"),
    page_size: int = Query(20, ge=1, le=100, description="Results per page (max 100)"),
    # Free-text search
    q: Optional[str] = Query(
        None, description="Search title, description, or crime number"
    ),
    # Sorting
    sort_by: str = Query("created_at", description="Sort field"),
    order: Literal["asc", "desc"] = Query("desc", description="Sort direction"),
    # Discrete filters
    status: Optional[CrimeStatus] = Query(None, description="Filter by status"),
    priority: Optional[Priority] = Query(None, description="Filter by priority"),
    category_id: Optional[uuid.UUID] = Query(
        None, description="Filter by category UUID"
    ),
    reporter_id: Optional[uuid.UUID] = Query(
        None, description="Filter by reporter UUID"
    ),
    # Date range filter on incident_date
    date_from: Optional[datetime] = Query(
        None, description="Incident date from (ISO 8601)"
    ),
    date_to: Optional[datetime] = Query(
        None, description="Incident date to (ISO 8601)"
    ),
    db: AsyncSession = Depends(get_db),
    current_user: User = _authenticated,
) -> PaginatedResponse[CrimeReportDetailResponse]:
    """
    Retrieve a paginated, fully-filtered list of crime reports.
    **All authenticated users.**

    Filter options
    --------------
    - `?q=theft` — full-text across title, description, crime_number
    - `?status=OPEN`
    - `?priority=HIGH`
    - `?category_id=<uuid>`
    - `?reporter_id=<uuid>`
    - `?date_from=2026-01-01&date_to=2026-12-31`

    Sortable by: `title`, `crime_number`, `incident_date`, `report_date`,
    `status`, `priority`, `victim_count`, `estimated_loss`, `created_at`.
    """
    result = await CrimeReportService.get_all(
        db,
        page=page,
        page_size=page_size,
        q=q,
        sort_by=sort_by,
        order=order,
        status=status,
        priority=priority,
        category_id=category_id,
        reporter_id=reporter_id,
        date_from=date_from,
        date_to=date_to,
    )
    return cast(Any, paginate(result))


@router.get(
    "/{report_id}",
    response_model=CrimeReportDetailResponse,
    summary="Get crime report by ID",
)
async def get_crime_report(
    report_id: uuid.UUID,
    db: AsyncSession = Depends(get_db),
    current_user: User = _authenticated,
) -> CrimeReportDetailResponse:
    """
    Retrieve a single crime report with nested reporter, category, and location.
    **All authenticated users.**
    """
    return cast(Any, await CrimeReportService.get_by_id(db, report_id))


@router.patch(
    "/{report_id}",
    response_model=CrimeReportDetailResponse,
    summary="Update crime report",
)
async def update_crime_report(
    report_id: uuid.UUID,
    payload: CrimeReportUpdate,
    request: Request,
    db: AsyncSession = Depends(get_db),
    current_user: User = _authenticated,
) -> CrimeReportDetailResponse:
    """
    Partially update a crime report.
    """
    return cast(Any, await CrimeReportService.update(
        db, report_id, payload, current_user, request
    ))


@router.delete(
    "/{report_id}",
    status_code=status.HTTP_204_NO_CONTENT,
    summary="Delete crime report",
)
async def delete_crime_report(
    report_id: uuid.UUID,
    request: Request,
    db: AsyncSession = Depends(get_db),
    current_user: User = _authenticated,
) -> None:
    """
    Soft-delete a crime report. **Admin only.**

    Returns **409 Conflict** if the report has status `ARCHIVED`.
    Archived reports are permanent records and cannot be deleted.
    Audit log is created automatically.
    """
    await CrimeReportService.delete(db, report_id, current_user, request)
