"""Add investigation management models

Revision ID: 1c231ba3e6a3
Revises: e0ddfbe4bf38
Create Date: 2026-07-20 22:19:56.824083

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1c231ba3e6a3'
down_revision: Union[str, Sequence[str], None] = 'e0ddfbe4bf38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('investigation_assignments',
    sa.Column('investigation_id', sa.Uuid(), nullable=False),
    sa.Column('investigator_id', sa.Uuid(), nullable=False),
    sa.Column('assigned_by', sa.Uuid(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('unassigned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assigned_by'], ['users.id'], name=op.f('fk_investigation_assignments_assigned_by_users')),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], name=op.f('fk_investigation_assignments_investigation_id_investigations')),
    sa.ForeignKeyConstraint(['investigator_id'], ['users.id'], name=op.f('fk_investigation_assignments_investigator_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_investigation_assignments'))
    )
    op.create_index(op.f('ix_investigation_assignments_id'), 'investigation_assignments', ['id'], unique=False)
    op.create_index(op.f('ix_investigation_assignments_investigation_id'), 'investigation_assignments', ['investigation_id'], unique=False)
    op.create_index(op.f('ix_investigation_assignments_investigator_id'), 'investigation_assignments', ['investigator_id'], unique=False)
    op.create_index(op.f('ix_investigation_assignments_is_active'), 'investigation_assignments', ['is_active'], unique=False)
    op.create_index(op.f('ix_investigation_assignments_is_deleted'), 'investigation_assignments', ['is_deleted'], unique=False)
    op.create_table('investigation_notes',
    sa.Column('investigation_id', sa.Uuid(), nullable=False),
    sa.Column('author_id', sa.Uuid(), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('attachment_evidence_id', sa.Uuid(), nullable=True),
    sa.Column('edited', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['attachment_evidence_id'], ['evidence.id'], name=op.f('fk_investigation_notes_attachment_evidence_id_evidence')),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name=op.f('fk_investigation_notes_author_id_users')),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], name=op.f('fk_investigation_notes_investigation_id_investigations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_investigation_notes'))
    )
    op.create_index(op.f('ix_investigation_notes_id'), 'investigation_notes', ['id'], unique=False)
    op.create_index(op.f('ix_investigation_notes_investigation_id'), 'investigation_notes', ['investigation_id'], unique=False)
    op.create_index(op.f('ix_investigation_notes_is_deleted'), 'investigation_notes', ['is_deleted'], unique=False)
    op.create_table('investigation_timeline',
    sa.Column('investigation_id', sa.Uuid(), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('performed_by', sa.Uuid(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], name=op.f('fk_investigation_timeline_investigation_id_investigations')),
    sa.ForeignKeyConstraint(['performed_by'], ['users.id'], name=op.f('fk_investigation_timeline_performed_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_investigation_timeline'))
    )
    op.create_index(op.f('ix_investigation_timeline_id'), 'investigation_timeline', ['id'], unique=False)
    op.create_index(op.f('ix_investigation_timeline_investigation_id'), 'investigation_timeline', ['investigation_id'], unique=False)
    op.create_index(op.f('ix_investigation_timeline_is_deleted'), 'investigation_timeline', ['is_deleted'], unique=False)
    op.add_column('evidence', sa.Column('bucket_name', sa.String(length=255), nullable=False))
    op.add_column('evidence', sa.Column('checksum', sa.String(length=64), nullable=True))
    op.add_column('evidence', sa.Column('file_extension', sa.String(length=20), nullable=True))
    op.add_column('investigations', sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='priority'), nullable=False))
    op.create_index(op.f('ix_investigations_investigator_id'), 'investigations', ['investigator_id'], unique=False)
    op.create_index(op.f('ix_investigations_report_id'), 'investigations', ['report_id'], unique=False)
    op.create_index(op.f('ix_investigations_status'), 'investigations', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_investigations_status'), table_name='investigations')
    op.drop_index(op.f('ix_investigations_report_id'), table_name='investigations')
    op.drop_index(op.f('ix_investigations_investigator_id'), table_name='investigations')
    op.drop_column('investigations', 'priority')
    op.drop_column('evidence', 'file_extension')
    op.drop_column('evidence', 'checksum')
    op.drop_column('evidence', 'bucket_name')
    op.drop_index(op.f('ix_investigation_timeline_is_deleted'), table_name='investigation_timeline')
    op.drop_index(op.f('ix_investigation_timeline_investigation_id'), table_name='investigation_timeline')
    op.drop_index(op.f('ix_investigation_timeline_id'), table_name='investigation_timeline')
    op.drop_table('investigation_timeline')
    op.drop_index(op.f('ix_investigation_notes_is_deleted'), table_name='investigation_notes')
    op.drop_index(op.f('ix_investigation_notes_investigation_id'), table_name='investigation_notes')
    op.drop_index(op.f('ix_investigation_notes_id'), table_name='investigation_notes')
    op.drop_table('investigation_notes')
    op.drop_index(op.f('ix_investigation_assignments_is_deleted'), table_name='investigation_assignments')
    op.drop_index(op.f('ix_investigation_assignments_is_active'), table_name='investigation_assignments')
    op.drop_index(op.f('ix_investigation_assignments_investigator_id'), table_name='investigation_assignments')
    op.drop_index(op.f('ix_investigation_assignments_investigation_id'), table_name='investigation_assignments')
    op.drop_index(op.f('ix_investigation_assignments_id'), table_name='investigation_assignments')
    op.drop_table('investigation_assignments')
    # ### end Alembic commands ###
