"""Add Phase 4 Crime Management schema

Revision ID: e0ddfbe4bf38
Revises: 91c308b3843c
Create Date: 2026-07-19 20:29:21.220479

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0ddfbe4bf38'
down_revision: Union[str, Sequence[str], None] = '91c308b3843c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
