"""
CrimeReport Pydantic Schemas
============================
All schemas are Pydantic v2.

Design decisions (per Phase 4 spec)
-------------------------------------
- reporter_id   REMOVED from Create — always auto-assigned from current_user.
- status        REMOVED from Create — always forced to OPEN by the service.
- crime_number  REMOVED from Create — auto-generated via PostgreSQL sequence.
- CrimeReportDetailResponse includes nested reporter/category/location objects,
  avoiding N+1 queries by relying on selectinload in the repository.
"""
from datetime import datetime, timezone
from typing import Optional
from uuid import UUID

from pydantic import BaseModel, ConfigDict, Field, field_validator

from app.core.enums.crime_status import CrimeStatus
from app.core.enums.priority import Priority


# ---------------------------------------------------------------------------
# Brief nested schemas embedded inside CrimeReportDetailResponse
# ---------------------------------------------------------------------------


class ReporterBrief(BaseModel):
    """Compact reporter view — avoids leaking sensitive user fields."""

    id: UUID
    email: str
    full_name: Optional[str] = None
    badge_number: Optional[str] = None

    model_config = ConfigDict(from_attributes=True)


class CategoryBrief(BaseModel):
    id: UUID
    name: str
    severity_level: int
    color_code: Optional[str] = None

    model_config = ConfigDict(from_attributes=True)


class LocationBrief(BaseModel):
    id: UUID
    latitude: float
    longitude: float
    address: Optional[str] = None
    landmark: Optional[str] = None
    city: str
    district: str
    state: str
    zip_code: Optional[str] = None

    model_config = ConfigDict(from_attributes=True)


# ---------------------------------------------------------------------------
# Inbound schemas
# ---------------------------------------------------------------------------


class CrimeReportCreate(BaseModel):
    """
    Validated payload for creating a new crime report.

    Intentionally omitted fields
    ----------------------------
    reporter_id   Auto-set to current_user.id by the service.
    status        Always forced to OPEN by the service.
    crime_number  Auto-generated by PostgreSQL sequence.
    """

    title: str = Field(..., min_length=5, max_length=255)
    description: str = Field(..., min_length=10)
    incident_date: datetime = Field(
        ..., description="Must be in the past; timezone-aware ISO 8601 datetime"
    )
    category_id: UUID
    location_id: UUID
    priority: Priority = Field(Priority.MEDIUM, description="Defaults to MEDIUM")
    victim_count: int = Field(0, ge=0)
    suspect_count: int = Field(0, ge=0)
    estimated_loss: float = Field(
        0.0, ge=0.0, description="Estimated financial loss in INR"
    )

    @field_validator("title", mode="before")
    @classmethod
    def strip_title(cls, v: str) -> str:
        return v.strip()

    @field_validator("incident_date", mode="before")
    @classmethod
    def validate_incident_date(cls, v: datetime) -> datetime:
        if isinstance(v, str):
            from datetime import datetime as dt
            v = dt.fromisoformat(v)
        if v.tzinfo is None:
            v = v.replace(tzinfo=timezone.utc)
        if v > datetime.now(timezone.utc):
            raise ValueError("incident_date cannot be in the future")
        return v


class CrimeReportUpdate(BaseModel):
    """
    Validated payload for partially updating an existing crime report.
    All fields are optional — only supplied fields are written.

    Intentionally excluded fields
    -----------------------------
    reporter_id   Never updatable.
    crime_number  Never updatable.
    """

    title: Optional[str] = Field(None, min_length=5, max_length=255)
    description: Optional[str] = Field(None, min_length=10)
    incident_date: Optional[datetime] = None
    status: Optional[CrimeStatus] = Field(
        None, description="Validated against transition matrix by the service"
    )
    priority: Optional[Priority] = None
    victim_count: Optional[int] = Field(None, ge=0)
    suspect_count: Optional[int] = Field(None, ge=0)
    estimated_loss: Optional[float] = Field(None, ge=0.0)
    category_id: Optional[UUID] = None
    location_id: Optional[UUID] = None

    @field_validator("title", mode="before")
    @classmethod
    def strip_title(cls, v: Optional[str]) -> Optional[str]:
        return v.strip() if v else v


# ---------------------------------------------------------------------------
# Outbound schemas
# ---------------------------------------------------------------------------


class CrimeReportResponse(BaseModel):
    """
    Compact outbound DTO — FK UUIDs only (no nested objects).
    Used in contexts where the nested data is not required.
    """

    id: UUID
    crime_number: str
    title: str
    description: str
    incident_date: datetime
    report_date: datetime
    status: CrimeStatus
    priority: Priority
    victim_count: int
    suspect_count: int
    estimated_loss: float
    reporter_id: UUID
    category_id: UUID
    location_id: UUID
    created_at: datetime
    updated_at: datetime
    is_deleted: bool

    model_config = ConfigDict(from_attributes=True)


class CrimeReportDetailResponse(BaseModel):
    """
    Full outbound DTO with nested reporter, category, and location objects.
    Used by POST, GET by ID, and PATCH endpoints.
    The repository eagerly loads relations via selectinload so no extra
    queries are triggered during serialisation.
    """

    id: UUID
    crime_number: str
    title: str
    description: str
    incident_date: datetime
    report_date: datetime
    status: CrimeStatus
    priority: Priority
    victim_count: int
    suspect_count: int
    estimated_loss: float
    reporter_id: UUID
    category_id: UUID
    location_id: UUID
    reporter: Optional[ReporterBrief] = None
    category: Optional[CategoryBrief] = None
    location: Optional[LocationBrief] = None
    created_at: datetime
    updated_at: datetime
    is_deleted: bool

    model_config = ConfigDict(from_attributes=True)
